// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lykykcjjilojxvduulrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5a3lrY2pqaWxvanh2ZHV1bHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzI4NzUsImV4cCI6MjA2MTYwODg3NX0.BTdDvSfO5jOdLFmbf_cTCsPSDQP1iO_kDOO6phApypo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);